plugins {
    id 'com.android.application'
}

android {
    namespace 'pe.chef.asistente'
    compileSdk 36

    defaultConfig {
        applicationId "pe.chef.asistente"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "0.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
